//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjInzynierski
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Accommodation
    {
        public Accommodation()
        {
            this.Person = new ObservableCollection<Person>();
            this.Person1 = new ObservableCollection<Person>();
        }
    
        public int ID { get; set; }
        public string street { get; set; }
        public string buildingNumber { get; set; }
        public int flatNumber { get; set; }
        public string city { get; set; }
        public string postCode { get; set; }
        public string country { get; set; }
    
        public virtual ObservableCollection<Person> Person { get; set; }
        public virtual ObservableCollection<Person> Person1 { get; set; }
    }
}
